-- MySQL Script generated by MySQL Workbench
-- Sun Sep 18 11:21:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SuperchargerDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SuperchargerDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SuperchargerDB` DEFAULT CHARACTER SET utf8 ;
USE `SuperchargerDB` ;

-- -----------------------------------------------------
-- Table `SuperchargerDB`.`AreaTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperchargerDB`.`AreaTrabajo` (
  `idAreaTrabajo` INT NOT NULL AUTO_INCREMENT,
  `nombreArea` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `especialidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idAreaTrabajo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperchargerDB`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperchargerDB`.`Empleados` (
  `idEmpleados` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `domicilio` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `idAreaTrabajo` INT NULL,
  `idAsistencia` INT NULL,
  PRIMARY KEY (`idEmpleados`),
  INDEX `areaTrabajo_idx` (`idAreaTrabajo` ASC) VISIBLE,
  CONSTRAINT `areaTrabajo`
    FOREIGN KEY (`idAreaTrabajo`)
    REFERENCES `SuperchargerDB`.`AreaTrabajo` (`idAreaTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperchargerDB`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperchargerDB`.`Clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `domicilio` VARCHAR(100) NULL,
  `dniTipo` VARCHAR(45) NULL,
  `dniNumero` INT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperchargerDB`.`Seguro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperchargerDB`.`Seguro` (
  `idSeguro` INT NOT NULL AUTO_INCREMENT,
  `nombreAseguradora` VARCHAR(100) NULL,
  `nroPoliza` VARCHAR(45) NULL,
  `titularPoliza` VARCHAR(100) NULL,
  PRIMARY KEY (`idSeguro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperchargerDB`.`Asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperchargerDB`.`Asistencia` (
  `idAsistencia` INT NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT NULL,
  `fechaFalta` DATE NULL,
  PRIMARY KEY (`idAsistencia`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `SuperchargerDB`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperchargerDB`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperchargerDB`.`Vehiculo` (
  `idVehiculo` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `idCliente` INT NULL,
  `idSeguro` INT NULL,
  PRIMARY KEY (`idVehiculo`),
  INDEX `idCliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `idAseguradora_idx` (`idSeguro` ASC) VISIBLE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `SuperchargerDB`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSeguro`
    FOREIGN KEY (`idSeguro`)
    REFERENCES `SuperchargerDB`.`Seguro` (`idSeguro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperchargerDB`.`Repuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperchargerDB`.`Repuestos` (
  `idRepuestos` INT NOT NULL AUTO_INCREMENT,
  `codigoComercial` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` INT NULL,
  PRIMARY KEY (`idRepuestos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperchargerDB`.`Trabajos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperchargerDB`.`Trabajos` (
  `idTrabajos` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(120) NULL,
  `tiempoTrabajo` TIME NULL,
  `precioHoraTrabajo` INT NULL,
  PRIMARY KEY (`idTrabajos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperchargerDB`.`FichaMecanica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperchargerDB`.`FichaMecanica` (
  `idFichaMecanica` INT NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT NULL,
  `idVehiculo` INT NULL,
  `idRepuestos` INT NULL,
  `idTrabajos` INT NULL,
  `fecha` DATE NULL,
  `comentarios` VARCHAR(120) NULL,
  PRIMARY KEY (`idFichaMecanica`),
  INDEX `idVehiculo_idx` (`idVehiculo` ASC) VISIBLE,
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  INDEX `idRepuestos_idx` (`idRepuestos` ASC) VISIBLE,
  INDEX `idTrabajo_idx` (`idTrabajos` ASC) VISIBLE,
  CONSTRAINT `idVehiculo`
    FOREIGN KEY (`idVehiculo`)
    REFERENCES `SuperchargerDB`.`Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEmpleados`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `SuperchargerDB`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRepuestos`
    FOREIGN KEY (`idRepuestos`)
    REFERENCES `SuperchargerDB`.`Repuestos` (`idRepuestos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTrabajo`
    FOREIGN KEY (`idTrabajos`)
    REFERENCES `SuperchargerDB`.`Trabajos` (`idTrabajos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperchargerDB`.`Cobros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperchargerDB`.`Cobros` (
  `idCobros` INT NOT NULL AUTO_INCREMENT,
  `idFichaMecanica` INT NULL,
  `nroFactura` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `monto` INT NULL,
  PRIMARY KEY (`idCobros`),
  INDEX `idFichaMecanica_idx` (`idFichaMecanica` ASC) VISIBLE,
  CONSTRAINT `idFichaMecanica`
    FOREIGN KEY (`idFichaMecanica`)
    REFERENCES `SuperchargerDB`.`FichaMecanica` (`idFichaMecanica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperchargerDB`.`Turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperchargerDB`.`Turnos` (
  `idTurnos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `idCliente` INT NULL,
  `idVehiculo` INT NULL,
  `idAreaTrabajo` INT NULL,
  PRIMARY KEY (`idTurnos`),
  INDEX `idClientes_idx` (`idCliente` ASC) VISIBLE,
  INDEX `idVehiculos_idx` (`idVehiculo` ASC) VISIBLE,
  INDEX `idAreaTrabajo_idx` (`idAreaTrabajo` ASC) VISIBLE,
  CONSTRAINT `idClientes`
    FOREIGN KEY (`idCliente`)
    REFERENCES `SuperchargerDB`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idVehiculos`
    FOREIGN KEY (`idVehiculo`)
    REFERENCES `SuperchargerDB`.`Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAreaTrabajo`
    FOREIGN KEY (`idAreaTrabajo`)
    REFERENCES `SuperchargerDB`.`AreaTrabajo` (`idAreaTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperchargerDB`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperchargerDB`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT NULL,
  `nombreUsuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `Empleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `SuperchargerDB`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
